### ISSUE TITLE
A simple question unrelated to this nice tutorial

### ISSUE THREAD

**Issue by shaoeric** [leandromoreira/ffmpeg-libav-tutorial#108]
Great work for me! Thanks for your sharing, but can i learn about how to draw the pictures in the repo? any tools?

**Comment by leandromoreira** [comment]
Thanks for the kind words, 😄 I really appreciate. 

In my case, I just draw into paper, took pictures (applied black and white filters), and compose them using google slides! :) (tbh I think, there must be other better methods to do it)

But if you just want to draw some flows, components, ... I'd point you to use mermaid-js instead, [github supports it](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) now, and it's really simple.

```mermaid
  graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```

```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>Bob: Hi Bob
    Bob->>Alice: Hi Alice
```

```mermaid
stateDiagram
    [*] --> Still
    Still --> [*]

    Still --> Moving
    Moving --> Still
    Moving --> Crash
    Crash --> [*]
```

**Comment by shaoeric** [comment]
very helpful for me :)
