### ISSUE TITLE
Unknown decoder 'libx264'

### ISSUE THREAD

**Issue by eggface-xyz** [leandromoreira/ffmpeg-libav-tutorial#110]
```
$ ffmpeg \
-y \ # global options
-c:a libfdk_aac -c:v libx264 \ # input options
-i bunny_1080p_60fps.mp4 \ # input url
-c:v libvpx-vp9 -c:a libvorbis \ # output options
bunny_1080p_60fps_vp9.webm # output url
```
complains 'Unknown decoder libx264'.
I think whatever goes into input options should be decoders, right? there's no such thing as libx264 as decoder anyway.
I am such a noob at ffmpeg.

**Comment by leandromoreira** [comment]
Hi @eggface-xyz you're right! I think your local `ffmpeg`installation doesn't have the proper decoder. Use the one available for you `ffmpeg -decoders | grep 264` some devices offer hardware decoding.

**Comment by eggface-xyz** [comment]
What I want to stress here is that libx264 is not decoder, it can only encode.
