### ISSUE TITLE
Mention the GPL lucense requirements

### ISSUE THREAD

**Issue by mattip** [leandromoreira/ffmpeg-libav-tutorial#12]
You may want to add a note that making a derivative work (linking) with GPL in your product will require you to release their sources to your end users https://softwareengineering.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application

**Comment by leandromoreira** [comment]
hi @mattip , thanks for the heads up but isn't it covered by the current license?

**Comment by mattip** [comment]
Your license is OK, I was thinking about something like this which you are free to use or adapt: 

```
Since the FFmpeg is so useful as a command line tool to do essential
tasks over the media files, how can we use it in our programs? 

The command line tool is built to work with stdin and stdout as pipes, or we can 
directly use the underlying libraries via a C API (appropiately wrapped for other
languages like C# or Python). There are reasons to choose loosely coupling it; 
FFmpeg is released under the GPL and also manages its own threads (on CPU 
or GPU) and memory space. If you choose to use the API, the rest of this tutorial
will get you started.
```

**Comment by mattip** [comment]
btw, feel free to close this if you don't think it is necessary

**Comment by leandromoreira** [comment]
Cool, I liked your suggestion! 👍
