### ISSUE TITLE
cli error

### ISSUE THREAD

**Issue by ofek** [leandromoreira/ffmpeg-libav-tutorial#13]
`ffmpeg -i input.mp4 output.avi` does transcode. You must provide the `copy` option on the streams you wish to keep lossless.

https://stackoverflow.com/questions/15049829/remux-to-mkv-but-add-all-streams-using-ffmpeg

**Comment by leandromoreira** [comment]
I leave an extra explanation to address that fact, the thing there is I was just showing how simple can be to use FFmpeg.

> We just made a remuxing here, which is converting from one container to another one. **Technically FFmpeg could be also be doing a transcoding but we'll talk about that later.**

**Comment by ofek** [comment]
Ah okay, my apologies! Perhaps we should bold that.
