### ISSUE TITLE
doc: format

### ISSUE THREAD

**Issue by Guaderxx** [leandromoreira/ffmpeg-libav-tutorial#134]
I don't sure is this what you actually want or a format issue

![image](https://github.com/user-attachments/assets/269e7d44-3e6a-441a-9c8b-a7e3c46118c3)

**Comment by leandromoreira** [comment]
it was intentional [codec](https://en.wikipedia.org/wiki/Codec) is a [portmanteau](https://en.wikipedia.org/wiki/Portmanteau) of encoder and decoder

**Comment by Guaderxx** [comment]
oh, thanks for your reply.
I get it now.
