### ISSUE TITLE
avformat_open_input always returns "Protocol not found" rv=(-1330794744)

### ISSUE THREAD

**Issue by HeartbreakSurvivor** [leandromoreira/ffmpeg-libav-tutorial#19]
Hi, I am new to ffmpeg and I have read your tutorials and it helps me a lot. When I get your code working in Visual Studio 2015 , I want to open a movie file named "mother1.mp4" which at the same directory where my main.c located, and I got the error as the title described above. 

`    int rv = avformat_open_input(&pFormatContext, "mother1.mp4", NULL, NULL);
    if (rv != 0) {
        av_strerror(rv, errbuf, sizeof(errbuf));
        logging("ERROR could not open the file: %s",errbuf);
        return -1;
    }`
Any ideas? Thanks.

**Comment by leandromoreira** [comment]
Hi @HeartbreakSurvivor can you try `file:mother1.mp4` or `file:fullpath`?

**Comment by HeartbreakSurvivor** [comment]
@leandromoreira 
Thanks for your reply, I have also tried this:
`int rv = avformat_open_input(&pFormatContext, "C:\Users\bigzh\Desktop\mother1.mp4", NULL, NULL);`
But still get the same error.
Now I can't figure out what happened to my project, is there is a problem with the movie file or the ffmpeg librarys which I download from [https://ffmpeg.zeranoe.com/builds/](url)

**Comment by HeartbreakSurvivor** [comment]
I think I may found the reason why I got this error. Because I compiled ffmpeg by myself and remove some useless modules but only h264 decoder left, maybe the input movie file is in other codec format. I have rebuild the ffmpeg and replace all the dll in my project and it works well.

**Comment by leandromoreira** [comment]
cool, nice to know @HeartbreakSurvivor can I close this one? feel free to post your impressions here. ;)

**Comment by HeartbreakSurvivor** [comment]
@leandromoreira  Hi, I am sorry to trouble you again and I have another question. Now I got the 8 *.pgm files, but how can I open them, I used some photo viewer, But It seems like transparent and display the background of the photo viewer. I also opened them with Notepad, but still can't show the grey image.

**Comment by leandromoreira** [comment]
@HeartbreakSurvivor I don't know any program to windows that does that but you can do two things:

1. View it online http://web.eecs.utk.edu/~smarz1/pgmview/
2. Convert it using FFmpeg `ffmpeg -i my.pgm my.jpg`

**Comment by HeartbreakSurvivor** [comment]
@leandromoreira Thank you very much and I will try it. you can close this one now.(*￣︶￣)
