### ISSUE TITLE
Please, can update code 0_hello_world.c  to play sound?

### ISSUE THREAD

**Issue by K3yn** [leandromoreira/ffmpeg-libav-tutorial#33]

**Comment by leandromoreira** [comment]
Hi @K3yn the purpose of the https://github.com/leandromoreira/ffmpeg-libav-tutorial/blob/master/0_hello_world.c is to extract frames and save them as images.

**Comment by K3yn** [comment]
sorry leandro, i adpated your code, i can display  video witch sdl2, but no audio :(, i try for 4 days :(.

I've been trying for 5 days without rest and without result
