### ISSUE TITLE
Disagreement with FFmpeg example

### ISSUE THREAD

**Issue by madphysicist** [leandromoreira/ffmpeg-libav-tutorial#44]
I am looking through 0_hello_world.c, [line 238](https://github.com/leandromoreira/ffmpeg-libav-tutorial/blob/master/0_hello_world.c#L238). According to the example in the latest FFmpeg docs, http://www.ffmpeg.org/doxygen/trunk/decode_video_8c-example.html, you don't need to unref the frame here. It's quite possible that I am misunderstanding the import of the comment

    /* the picture is allocated by the decoder. no need to
       free it */

in the FFmpeg version of `decode()`.

Overall, awesome tutorial. I found it extremely helpful despite any impression my nitpicking may give to the contrary. I can't wait to see it grow in both content and popularity.

**Comment by leandromoreira** [comment]
I agree with you the [docs point to this](https://ffmpeg.org/doxygen/trunk/group__lavc__decoding.html#ga11e6542c4e66d3028668788a1a74217c):

```
int avcodec_receive_frame(AVCodecContext * avctx, AVFrame *frame)
# frame  This will be set to a  reference-counted video or audio frame 
(depending on the decoder type)  allocated by the decoder. 
Note that the function will always call  av_frame_unref(frame) 
before doing anything else.

```
