### ISSUE TITLE
ffmpeg -i <filename> -filter:v fps=fps=30 <filename>

### ISSUE THREAD

**Issue by niektuytel** [leandromoreira/ffmpeg-libav-tutorial#72]
dear,

the given command in the title should create a new file with a proper frame rate, 
how ever my question is is this also possible with c++, and what i have to use re-muxing ?
or more thinking about muxing?

thanks in advance for helping,
(would be awesome if you give some sample code, :) )

kind regards,

Niek

**Comment by leandromoreira** [comment]
Hi there @niektuytel you need to transcode, the third part of [this tutorial explains a simple example](https://github.com/leandromoreira/ffmpeg-libav-tutorial#chapter-3---transcoding).

**Comment by niektuytel** [comment]
thanks, it is working now
