### ISSUE TITLE
make fetch_small_bunny_video not working

### ISSUE THREAD

**Issue by FransM** [leandromoreira/ffmpeg-libav-tutorial#76]
I tried 
make fetch_small_bunny_video
but it fails. This is on ubuntu 20.04.

FIrst issue was that apparently my command processor is not dash. I fixed this by adding 
#!/bin/bash 
at the beginning of ./fetch_bbb_video.sh

Next I got a not authorized from distribution.bbb3d.renderfarming.net
Here google helped me by giving me a local mirror from which I could fetch it. Probably the url needs updating.
Or maybe make the small_bunny_1080p_60fps.mp4 available somewhere (it is only 3.2 M)

BTW: nice tutorial; thank you

**Comment by leandromoreira** [comment]
thanks @FransM yes =( unfortunately the files aren't in the same place, I wonder if we can host it on a github repo (a new one)

**Comment by FransM** [comment]
I think probably the best solution is to create a new github repo with the small file.
Best create this under your account as that will give you full control

Alternative is to use a location where it is unlikely that the file disappears.
I used 
http://ftp.nluug.nl/graphics/blender/demo/movies/BBB/bbb_sunflower_1080p_60fps_normal.mp4
as that is quite local to me, but probably there is a better place.

For using bash in the script I created a small change and submitted a pull request:
See https://github.com/leandromoreira/ffmpeg-libav-tutorial/pull/77

**Comment by leandromoreira** [comment]
@FransM I'm going to try to stick to https://github.com/leandromoreira/big-buck-bunny/raw/main/Big-Buck-Bunny-1080p-h264-4mb-60fps-multi-ch-ac3.mp4

**Comment by FransM** [comment]
Looks good to me!

**Comment by leandromoreira** [comment]
https://github.com/leandromoreira/ffmpeg-libav-tutorial/commit/754d9333ce876b9e0b581f3d3559f921a546880b
