### ISSUE TITLE
Bad link in README

### ISSUE THREAD

**Issue by Tessag159** [leandromoreira/ffmpeg-libav-tutorial#88]
In the README there is a line that uses wget to download a large mp4 file. 
`wget -O bunny_1080p_60fps.mp4 http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4`
This command results in a 403 forbidden error.

`wget -O bunny_1080p_60fps.mp4 https://mirror.clarkson.edu/blender/demo/movies/BBB/bbb_sunflower_1080p_60fps_normal.mp4`
is an alternative mirror to the same file.

**Comment by leandromoreira** [comment]
thanks a lot @Tessag159 , these links often goes up and then suddenly they go down =( that's why i added the small_bunny_1080p_60fps.mp4 file  =)

**Comment by Tessag159** [comment]
Ah. I didn't notice you added it to the source code. All is good here then, no bug!
