### ISSUE TITLE
[Question] About libavformat avio, How to use custom asynchronous IO.

### ISSUE THREAD

**Issue by ChinaChenMingQuan** [leandromoreira/ffmpeg-libav-tutorial#92]
Note: It is asynchronous IO, not synchronous IO.

**Comment by leandromoreira** [comment]
hi there @ChinaChenMingQuan this might not be related directly with ffmpeg/libav, but [by using avio](https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/avio_reading.c#L42) + [c async io](https://www.gnu.org/software/libc/manual/html_node/Asynchronous-I_002fO.html), isnt?

But if that's not the case, [I found this seek async piece of code](https://ffmpeg.org/doxygen/trunk/async_8c_source.html#l00386), it might help you.

**Comment by ChinaChenMingQuan** [comment]
@leandromoreira, I need asynchronous IO like the C# language. 

Example:  

1. Pseudocode:
await fread_async(buffer, 1, count, handle_stream); 
await av_read_frame_async(pFormatContext, pPacket);

2. C Code:
fread_async(buffer, 1, count, handle_stream, callback_on_completion); 
av_read_frame_async(pFormatContext, pPacket, callback_on_completion);

3. C++ Code:
co_await fread_async(buffer, 1, count, handle_stream); 
co_await av_read_frame_async(pFormatContext, pPacket);

**Comment by ChinaChenMingQuan** [comment]
I want to call the FFmpeg API, Don't want to change the FFmpeg code. I don't like the GPL.

**Comment by ChinaChenMingQuan** [comment]
But FFmpeg API avio_alloc_context does not support asynchronous IO. It's so hard to find a modern codec library.

**Comment by ChinaChenMingQuan** [comment]
@leandromoreira, FFmpeg has no asynchronous IO. Server needs asynchronous IO to wait for client code. Cannot host a client in one thread.

**Comment by ChinaChenMingQuan** [comment]
@leandromoreira, Only multiple processes can be selected to solve. If you have a method, I hope you can give an example.
