### ISSUE TITLE
Segment fault when transcode mp4 with no audio stream

### ISSUE THREAD

**Issue by blackrose28** [leandromoreira/ffmpeg-libav-tutorial#93]
When the mp4 video has no audio stream, the 3_trancoding crash

**Comment by leandromoreira** [comment]
Hi, there @blackrose28. It's because, in this example, we assumed [a container would always have an audio stream](https://github.com/leandromoreira/ffmpeg-libav-tutorial/blob/master/3_transcoding.c#L114). :) It shouldn't be hard do change though.

**Comment by blackrose28** [comment]
Sure, just close this issue if you think it's not important
