### ISSUE TITLE
Transcoding: fmp4 delay_moov

### ISSUE THREAD

**Issue by alexLopatin** [leandromoreira/ffmpeg-libav-tutorial#94]
Hi Leandro!
Thanks for this awesome tutorial, it really saved me a lot of time understanding ffmpeg.
But there is a problem with the transcoding example. When transcoding to fragmented mp4, the encoder context doesn't supply full info to output stream, resulting in next error:

> ffmpeg : [extract_extradata @ 00000243f19d6e00] No start code is found.
> broken_test.mp4: could not find codec parameters
> [h264 @ 00000243f19d67c0] No start code is found.
> [h264 @ 00000243f19d67c0] Error splitting the input into NAL units.
> [h264 @ 00000243f19ede80] No start code is found.
> [h264 @ 00000243f19ede80] Error splitting the input into NAL units.
> [h264 @ 00000243f1a742c0] sps_id 15 out of range
> [h264 @ 00000243f1a742c0] no frame!
> [h264 @ 00000243f19f28c0] No start code is found.
> [h264 @ 00000243f19f28c0] Error splitting the input into NAL units.
> [h264 @ 00000243f19f3180] no frame!
> [h264 @ 00000243f1a7d2c0] no frame!
> [h264 @ 00000243f19f3b00] slice type 15 too large at 1
> [h264 @ 00000243f19f3b00] decode_slice_header error
> [h264 @ 00000243f19f3b00] no frame!
> [h264 @ 00000243f19f44c0] No start code is found.
> [h264 @ 00000243f19f44c0] Error splitting the input into NAL units.

So, with setting movflags=delay_moov everything works fine. I think it's because I'm using a newer version of x264. Anyway, should this flag set on in transcoding example?

**Comment by leandromoreira** [comment]
hi there @alexLopatin I'm glad this is useful for you.

I didn't find this option on the [documentation](https://ffmpeg.org/ffmpeg-formats.html#Options-11) but saw this on the [movencoder](https://github.com/FFmpeg/FFmpeg/blob/127c40c9ca90dfe03cde0181f1e6654813a4b2b7/libavformat/movenc.c#L78) and it's even the default usage for the [hls encoder](https://github.com/FFmpeg/FFmpeg/blob/ab658db4d06fa5a3ef5b218e0b86970738e33016/libavformat/hlsenc.c#L937). Good catch :)

Do you want to make a PR for this?
