### ISSUE TITLE
Why is there a while loop when decoding packets hello_world

### ISSUE THREAD

**Issue by LentilStew** [leandromoreira/ffmpeg-libav-tutorial#96]
![image](https://user-images.githubusercontent.com/52719903/121712210-df576180-cab1-11eb-9d75-ba60b1d1fc86.png)
decode_packet() function in the 0_hello_world.c file
what does that while loop do?
Can a packet contain more than one frame?

**Comment by TOTON95** [comment]
@LentilStew if I'm not wrong, this while loop is to send raw compressed AvPackets to the decoder until the multimedia source is no longer able to provide them, at this point `response` would be a negative number and you'll to figure out if the packet is bad or we already reached an EOF situation.

**Comment by leandromoreira** [comment]
I think you can also see it like this:

```
# DTS - the order the frames are sent (i.e. B x frame depends on previsou I and next P ... and so )
5,2,1,3,

# PTS - the order the frames must be presented (i.e. the way you want to see the frames)
1,2,3,4,5,6
```

Therefore in order for you to decode the "first frame" (PTS order) you might need to open and decode more other frames/packets.
