### ISSUE TITLE
Overlay shape while transcoding video

### ISSUE THREAD

**Issue by LentilStew** [leandromoreira/ffmpeg-libav-tutorial#98]
I added this function in 3_transcoding.c
![image](https://user-images.githubusercontent.com/52719903/122688227-6bbffd80-d1f1-11eb-8834-8cc4203265da.png)
It's called to draw an square in every frame it only changes the Y of the YUV file, I made it just to see if I could overlay images this way
![FirstFrame](https://user-images.githubusercontent.com/52719903/122688199-403d1300-d1f1-11eb-9997-6c752d62e1e9.png)
This is the fist frame of the video, screenshot from VLC^^
![LastFrame](https://user-images.githubusercontent.com/52719903/122688201-416e4000-d1f1-11eb-8de6-1ccec5598871.png)
This is the last frame of the video, screenshot from VLC^^
![frame-1423836064](https://user-images.githubusercontent.com/52719903/122688219-5a76f100-d1f1-11eb-86f3-2f0b2e991097.jpg)
This is the pgm output of the save_gray_frame function^^
![frame-654704535](https://user-images.githubusercontent.com/52719903/122688220-5b0f8780-d1f1-11eb-8e74-acd1391bdfb6.jpg)
This is another example of the save_gray_Frame function ^^
Is this the intended way to overlay images?, Are there other ways of doing it? 
I imagine that the image is weird because of the compression
![image](https://user-images.githubusercontent.com/52719903/122688415-76c75d80-d1f2-11eb-98ec-efeb4dced949.png)

**Comment by leandromoreira** [comment]
hi @LentilStew nice addition, usually the overlay is handled by the [ffmpeg filtering](https://ffmpeg.org/ffmpeg-filters.html#Examples-89) (my intent is to do a next chapter on that).

But you [can see filtering in action on github](https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/filtering_video.c).

**Comment by LentilStew** [comment]
If anyone wants to overlay the image this way, without it being ugly, you have to copy the frame
![image](https://user-images.githubusercontent.com/52719903/122801925-1c360c00-d29b-11eb-9b3c-d98c6ee3841e.png)
and send the encoder a copy of the frame Remember to free the new frame

**Comment by leandromoreira** [comment]
cool @LentilStew thanks for sharing!

Why do you need to copy format, width... even using the `av_frame_copy_props`? (I don't know this API, just curious, by its name I suppose it should copy all the properties, I'm guessing)

**Comment by LentilStew** [comment]
I copied the code from here [stackoverflow](https://stackoverflow.com/questions/38808946/copying-a-decoded-ffmpeg-avframe)

But the av_frame_get_buffer() function says that "format (pixel format for video, sample format for audio)- width and height for video- nb_samples and channel_layout for audio" must be set before calling the function

and the function av_frame_copy_props() says that it does not copy pts, sample rate (for audio) or sample aspect ratio (for video), but not width/height or channel layout. Side data is also copied. 

the av_frame_copy_props() only copies "metadata" fields from src to dst
